# Generated by Django 5.0.6 on 2024-06-07 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='perro',
            fields=[
                ('cod_perro', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_perro', models.CharField(max_length=20)),
                ('edad_perro', models.IntegerField()),
                ('raza_perro', models.CharField(max_length=30)),
                ('esterelizacion', models.BooleanField(verbose_name=True)),
                ('fecha_nac', models.DateField()),
            ],
        ),
    ]
