# Generated by Django 4.2.1 on 2023-06-12 02:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sexo',
            fields=[
                ('id_sexo', models.AutoField(db_column='idSexo', primary_key=True, serialize=False)),
                ('sexo', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id_mascota', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre_mascota', models.CharField(max_length=20)),
                ('fecha_nacimiento', models.DateField()),
                ('raza_mascota', models.CharField(max_length=20)),
                ('id_sexo', models.ForeignKey(db_column='idSexo', on_delete=django.db.models.deletion.CASCADE, to='Gatos.sexo')),
            ],
        ),
    ]
