# Generated by Django 5.0.6 on 2024-06-07 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gato',
            fields=[
                ('cod_gato', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_gato', models.CharField(max_length=20)),
                ('edad_gato', models.IntegerField()),
                ('raza_gato', models.CharField(max_length=30)),
                ('esterelizacion', models.BooleanField(blank=True, null=True)),
                ('fecha_nac', models.DateField()),
            ],
        ),
    ]
