# Generated by Django 5.0.6 on 2024-06-18 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gatos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id_mascota', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre_mascota', models.CharField(max_length=20)),
                ('fecha_nacimiento', models.DateField()),
                ('raza_mascota', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Sexo',
            fields=[
                ('id_sexo', models.AutoField(db_column='idSexo', primary_key=True, serialize=False)),
                ('sexo', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Gato',
        ),
        migrations.AddField(
            model_name='mascota',
            name='id_sexo',
            field=models.ForeignKey(db_column='idSexo', on_delete=django.db.models.deletion.CASCADE, to='Gatos.sexo'),
        ),
    ]
