# Generated by Django 5.0.6 on 2024-06-18 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gatos', '0002_mascota_sexo_delete_gato_mascota_id_sexo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='nombre_mascota',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
