# Generated by Django 5.0.6 on 2024-06-18 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gatos', '0003_alter_mascota_nombre_mascota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='fecha_nacimiento',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='raza_mascota',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
